#!/bin/sh

basedir="/sys/class/backlight/"					# base dir for backlight class
handler="$basedir$(ls $basedir)/"				# get the backlight handler
old_brightness=$(cat "$handler""brightness")			# get current brightness
max_brightness=$(cat "$handler""max_brightness")			# get max brightness
old_brightness_p=$(( 100 * old_brightness / max_brightness ))	# get current brightness %
new_brightness_p=${1:-old_brightness_p}			# calculate new brightness % 
[ "$new_brightness_p" -ge 99 ] && new_brightness_p=99		# restricting max brightness
[ "$new_brightness_p" -le 1 ] && new_brightness_p=1		# restricting min brightness
new_brightness=$(( max_brightness * new_brightness_p / 100 )) # calculate new brightness value
echo "$new_brightness"
# chmod 666 $handler"brightness"					# change file permission to write
echo $new_brightness > "$handler""brightness"			# set the new brightness value
