#!/bin/sh
status=$(cat /sys/class/power_supply/BAT0/status)
capacity=$(cat /sys/class/power_supply/BAT0/capacity)
capacity=$((capacity))
if [ "$status" = "Charging" ]; then
  if [ $capacity -ge 90 ]; then
    icon=""
  elif [ $capacity -ge 80 ]; then
    icon=""
  elif [ $capacity -ge 60 ]; then
    icon=""
  elif [ $capacity -ge 40 ]; then
    icon=""
  elif [ $capacity -ge 30 ]; then
    icon=""
  elif [ $capacity -ge 20 ]; then
    icon=""
  else
    icon=""
  fi

elif [ "$status" = "Discharging" ]; then
  if [ $capacity -ge 90 ]; then
    icon=""
  elif [ $capacity -ge 80 ]; then
    icon=""
  elif [ $capacity -ge 70 ]; then
    icon=""
  elif [ $capacity -ge 60 ]; then
    icon=""
  elif [ $capacity -ge 50 ]; then
    icon=""
  elif [ $capacity -ge 40 ]; then
    icon=""
  elif [ $capacity -ge 30 ]; then
    icon=""
  elif [ $capacity -ge 20 ]; then
    icon=""
  elif [ $capacity -ge 10 ]; then
    icon=""
  else
    icon=""
  fi
elif [ "$status" == "Full" ]; then
  icon='⚡'
else
  icon=""
fi
	# printf "%s%s" "$capacity%" "$status"; unset warn
printf "%s %s" "$capacity%" "$icon";
