#!/bin/sh

hour=$(date '+%I')
case "$hour" in
	"00") icon="🕛" ;;
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac
min=$(date '+%M')
# [[ "$min" -lt 10 ]] && min="0$min"
m=$(date "+%p")
time="$hour:$min$m $icon"
[ "$min" -lt 1 ] && notify-send "Time" "$time"
echo "$time"
